[build]
builder = "nixpacks"
buildCommand = "pnpm install && pnpm exec prisma generate && pnpm run build"

[deploy]
startCommand = "pnpm run start"
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"
